//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.06 at 02:11:43 PM IST 
//


package com.java.xml.school.dept;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DepartmentVo" type="{http://www.java.com/xml/school/dept}DepartmentVo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "departmentVo"
})
@XmlRootElement(name = "CreateDeptRequest")
public class CreateDeptRequest {

    @XmlElement(name = "DepartmentVo", required = true)
    protected DepartmentVo departmentVo;

    /**
     * Gets the value of the departmentVo property.
     * 
     * @return
     *     possible object is
     *     {@link DepartmentVo }
     *     
     */
    public DepartmentVo getDepartmentVo() {
        return departmentVo;
    }

    /**
     * Sets the value of the departmentVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DepartmentVo }
     *     
     */
    public void setDepartmentVo(DepartmentVo value) {
        this.departmentVo = value;
    }

}
