//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.06 at 02:11:43 PM IST 
//


package com.java.xml.school.dept;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.java.xml.school.dept package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.java.xml.school.dept
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateDeptResponse }
     * 
     */
    public UpdateDeptResponse createUpdateDeptResponse() {
        return new UpdateDeptResponse();
    }

    /**
     * Create an instance of {@link UpdateDepartmentVo }
     * 
     */
    public UpdateDepartmentVo createUpdateDepartmentVo() {
        return new UpdateDepartmentVo();
    }

    /**
     * Create an instance of {@link CreateDeptResponse }
     * 
     */
    public CreateDeptResponse createCreateDeptResponse() {
        return new CreateDeptResponse();
    }

    /**
     * Create an instance of {@link DepartmentVo }
     * 
     */
    public DepartmentVo createDepartmentVo() {
        return new DepartmentVo();
    }

    /**
     * Create an instance of {@link UpdateDeptRequest }
     * 
     */
    public UpdateDeptRequest createUpdateDeptRequest() {
        return new UpdateDeptRequest();
    }

    /**
     * Create an instance of {@link DeleteDeptRequest }
     * 
     */
    public DeleteDeptRequest createDeleteDeptRequest() {
        return new DeleteDeptRequest();
    }

    /**
     * Create an instance of {@link StudentDetailsResponse }
     * 
     */
    public StudentDetailsResponse createStudentDetailsResponse() {
        return new StudentDetailsResponse();
    }

    /**
     * Create an instance of {@link StudentDetailsRequest }
     * 
     */
    public StudentDetailsRequest createStudentDetailsRequest() {
        return new StudentDetailsRequest();
    }

    /**
     * Create an instance of {@link CreateDeptRequest }
     * 
     */
    public CreateDeptRequest createCreateDeptRequest() {
        return new CreateDeptRequest();
    }

    /**
     * Create an instance of {@link DeleteDeptResponse }
     * 
     */
    public DeleteDeptResponse createDeleteDeptResponse() {
        return new DeleteDeptResponse();
    }

    /**
     * Create an instance of {@link StudentVo }
     * 
     */
    public StudentVo createStudentVo() {
        return new StudentVo();
    }

    /**
     * Create an instance of {@link UpdateStudentVo }
     * 
     */
    public UpdateStudentVo createUpdateStudentVo() {
        return new UpdateStudentVo();
    }

}
